[Feature/#17] 로그인 페이지, 회원가입 방법 선택 페이지
woowa-techcamp-2021/store-1 pull request #19
Opened 2021-08-13 08:58 UTC by CurlyBat

## :bookmark_tabs: 제목

![Aug-13-2021 17-57-14](https://user-images.githubusercontent.com/82671736/129332298-cc865aa1-d144-4c12-8473-ccf21b0de506.gif)

## :heavy_check_mark: 셀프 체크리스트

> ~최소 2명 이상의 assign을 받아야만 Merge 가능합니다.~

- [x] Warning Message가 발생하지 않았나요?
- [x] Coding Convention을 준수했나요?

## :speech_balloon: 작업 내용

> 구현 내용 및 작업 했던 내역

- 로그인 페이지
- 회원가입 방법 선택 페이지

## :construction: PR 특이 사항

> PR을 볼 때 주의깊게 봐야하거나 말하고 싶은 점

- 페이지 구현을 이런식으로 해서 추후 컴포넌트를 나누는 식으로 할 수 있게끔 짜여졌는지?

## 🕰 실제 소요 시간

> 2 mh

2021-08-13 09:11 UTC, cothis approved these changes
잘 봤습니다! 디자인도 이쁘네요

2021-08-13 09:11 UTC, cothis commented on client/src/pages/Signin.tsx
> +  &:focus {
이게 scss 문법인가요?

2021-08-13 09:11 UTC, cothis commented on client/src/pages/Signin.tsx
> +  width: 303px;
당장은 아니더라도반응형으로 가려면 이런 고정값은 추후 바껴야 할 것 같아요..

2021-08-13 09:11 UTC, cothis commented on client/src/pages/Signin.tsx
> +  font-family: NotoSans, nanumgothic, '나눔고딕', Malgun Gothic, '맑은 고딕', AppleGothic, Dotum, '돋움', sans-serif;
아마 폰트는 전역으로 설정하지 않을까요?

2021-08-13 09:11 UTC, cothis commented on client/src/styles/global-style.ts
> +    font-family: NotoSans, nanumgothic,"나눔고딕",Malgun Gothic,"맑은 고딕",AppleGothic,Dotum,"돋움",sans-serif;
아예 * 에 폰트설정해도 괜찮지 않을까..라고 생각합니다

2021-08-13 09:13 UTC, CurlyBat commented on client/src/pages/Signin.tsx
> +  &:focus {
네 맞습니다

2021-08-13 09:14 UTC, CurlyBat commented on client/src/pages/Signin.tsx
> +  width: 303px;
안그래도 이부분도 여쭙고싶기는 했습니다.. 반응형으로 설계해본 적이 없어서 이렇게 스타일링 해도 되는지

아니면 다른 방식을 써야하는지..

혹 추천하시는 방향이 있을까요?

2021-08-13 09:14 UTC, CurlyBat commented on client/src/pages/Signin.tsx
> +  font-family: NotoSans, nanumgothic, '나눔고딕', Malgun Gothic, '맑은 고딕', AppleGothic, Dotum, '돋움', sans-serif;
네 이부분은 상의 후 빼려고 합니다

2021-08-16 07:03 UTC, jiyong1 commented on client/src/pages/Signin.tsx
> +  width: 303px;
괜찮습니다 Signin 페이지는 애초에 300px 정도라면 모든 페이지에서 같은 크기로 보일 겁니다 ㅎㅎ

2021-08-16 07:04 UTC, jiyong1 commented on client/src/pages/Signin.tsx
> +  font-family: NotoSans, nanumgothic, '나눔고딕', Malgun Gothic, '맑은 고딕', AppleGothic, Dotum, '돋움', sans-serif;
폰트 전역으로 설정하고 Noto sans kr 이랑 Do Hyeon 체 구글에서 가져오면 좋을 것 같아요

2021-08-16 07:04 UTC, jiyong1 requested changes
폰트 전역으로 추가해주시면 감사하겠습니다 ~~

2021-08-16 07:41 UTC, jiyong1 approved these changes
고생하셨습니다 ! 리뷰에 질문하나 있는데 확인해주세요 ~~

2021-08-16 07:41 UTC, jiyong1 commented on client/webpack/webpack.config.common.ts
> +        test: /\.(woff|woff2|eot|ttf|otf)$/,
폰트 때문에 추가한 거군요.. 저는 혹시 이미지 때문인지 들어왔는데ㅎㅎ 고생하셨습니다!

2021-08-16 07:41 UTC, jiyong1 commented on client/src/styles/global-style.ts
> +      font-family: 'NotoSans', 'DoHyeon', sans-serif;
이렇게 두개 추가하면 어떻게 되는건가요 ?!

2021-08-16 07:45 UTC, CurlyBat commented on client/src/styles/global-style.ts
> +      font-family: 'NotoSans', 'DoHyeon', sans-serif;
https://developer.mozilla.org/ko/docs/Web/CSS/font-family

font-family는 가장 앞에꺼부터 가능한 폰트를 사용하는 식으로 되어있기 때문에 기본적으로는 noto-sans를 이용하게 될 것입니다.

2021-08-16 07:47 UTC, jiyong1 commented on client/src/styles/global-style.ts
> +      font-family: 'NotoSans', 'DoHyeon', sans-serif;
그럼 그냥 noto sans를 기본적으로 사용하고 도현체가 필요한 부분만 font family 지정해주는게 좋지 않을까요 ?!

2021-08-16 07:47 UTC, jiyong1 commented on client/src/styles/global-style.ts
> +      font-family: 'NotoSans', 'DoHyeon', sans-serif;
도현체가 워낙 개성이 강해서 필요한 부분에서만 사용할 것 같은데

2021-08-16 07:52 UTC, CurlyBat commented on client/src/styles/global-style.ts
> +      font-family: 'NotoSans', 'DoHyeon', sans-serif;
기본적으로는 noto sans만 들어가니까 전역으로는 그냥 저 폰트까지 지원한다 정도의 느낌으로 일단 넣어놨었습니다.

아마 noto sans 폰트가 로딩이 안되는 상황이 만약에 생긴다면 도현 폰트도 로딩이 안될 가능성이 높아서 sans-serif로 넘어갈거라 예상이 되어서..

그래도 빼는게 낫다 생각되시면 빼겠습니다

2021-08-17 01:08 UTC, merged