[feature/#4] 기본적인 설정파일 추가
woowa-techcamp-2021/store-1 pull request #5
Opened 2021-08-10 02:41 UTC by TsooranKim

## :bookmark_tabs: 제목

기본적인 설정파일 추가

## :heavy_check_mark: 셀프 체크리스트

> ~최소 2명 이상의 assign을 받아야만 Merge 가능합니다.~

- [x] Warning Message가 발생하지 않았나요?
- [x] Coding Convention을 준수했나요?

## :speech_balloon: 작업 내용

> 구현 내용 및 작업 했던 내역

- .prettierrc 설정
- .devcontainer 설정
- .gitignore
- .editorconfig 추가

## :construction: PR 특이 사항

> PR을 볼 때 주의깊게 봐야하거나 말하고 싶은 점

- 현재 서버쪽 devcontainer가 docker-compose로 연결하여 git이 parent에서 전파되지 않는 문제가 있습니다.

## 🕰 실제 소요 시간

> 30m

2021-08-10 04:12 UTC, cothis requested changes
server/.editorconfig
.gitignore
두파일에 줄바꿈만 추가해주시면 좋을것 같아요!!

2021-08-10 04:15 UTC, jiyong1 approved these changes
김태균의 도커 강의 잘들었습니다 !

2021-08-10 04:25 UTC, cothis approved these changes

2021-08-10 04:40 UTC, CurlyBat approved these changes

2021-08-10 05:04 UTC, cothis approved these changes

2021-08-10 07:13 UTC, TsooranKim commented
> server/.editorconfig
> .gitignore
> 두파일에 줄바꿈만 추가해주시면 좋을것 같아요!!

반영했습니다!

2021-08-10 07:13 UTC, merged

2021-08-13 06:26 UTC, negu63 reviewed
도커 정말 신기하네요 ㄷㄷ 도커를 만들어 놓으면 새로운 프로젝트를 할 때 재활용도 가능한가요?

2021-08-13 06:27 UTC, cothis commented
물론이죠!