[feature/#79] 엔티티 개발
woowa-techcamp-2021/store-1 pull request #80
Opened 2021-08-22 15:02 UTC by cothis

## :bookmark_tabs: 제목

엔티티들 개발했습니다.

## :heavy_check_mark: 셀프 체크리스트

> ~최소 2명 이상의 assign을 받아야만 Merge 가능합니다.~

- [x] Warning Message가 발생하지 않았나요?
- [x] Coding Convention을 준수했나요?

## :speech_balloon: 작업 내용

> 구현 내용 및 작업 했던 내역

- BoardContent Entity
- BoardComment Entity
- Category Entity
- Review Entity
- Order Entity
- OrderHasProduct Entity
- OrderHistory Entity
- Cart Entity
- CartHasProduct Entity
- Hello message 출력 코드 삭제(이건 이 이슈랑 관계없는 것)

## :construction: PR 특이 사항

> PR을 볼 때 주의깊게 봐야하거나 말하고 싶은 점

- 아직 실제 module 에 등록하지 않아서, 테스트는 못해봤습니다. 기본적인 엔티티만 최대한 맞춰서 만들어봤어요.

## 🕰 실제 소요 시간

> 3 mh

2021-08-22 15:15 UTC, jiyong1 requested changes
전에 제품 하나에 여러개 카테고리 묶어야 할 것 같다고 말씀드렸는데 확인 부탁드립니다 ~
그리고 제품에 tags 도 들어가지 않나요 ?!

2021-08-22 15:15 UTC, jiyong1 commented on server/src/models/product/entities/product.entity.ts
> +  category: Category;
category 는 many to many로 해야될 것 같은데.. 어떻게 생각하시나요 ?!

2021-08-22 15:16 UTC, TsooranKim commented on server/src/models/product/entities/product.entity.ts
> +  category: Category;
여러개로 되게 해야하는게 맞아요~

2021-08-22 15:18 UTC, cothis commented on server/src/models/product/entities/product.entity.ts
> +  category: Category;
제품 하나가 여러 하위 카테고리를 가져야된다는 말씀이시죠?

2021-08-22 15:20 UTC, cothis commented on server/src/models/product/entities/product.entity.ts
> +  category: Category;
tags는 어떤 내용인지 알수있을까요? ㅜㅜ

2021-08-22 15:21 UTC, CurlyBat commented on server/src/models/product/entities/product.entity.ts
> +  category: Category;
green, new 이런 태그 말씀하시는거 아닐까요?

2021-08-22 15:22 UTC, TsooranKim commented on server/src/models/product/entities/product.entity.ts
> +  category: Category;
```typescript
type Tag = 'best' | 'green' | 'new' | 'sale' | 'soldout' | 'disabled';
```
입니다!

2021-08-22 15:22 UTC, jiyong1 commented on server/src/models/product/entities/product.entity.ts
> +  category: Category;
맞습니당 ~~ enum으로 그때 했던 것 같은데
notion에 API 목록 보시면 좋을 것 같아요 !

2021-08-22 15:22 UTC, cothis commented on server/src/models/product/entities/product.entity.ts
> +  category: Category;
아하!! 
추가하겠습니다. enum 배열로 넣어도 될까요? 아니면 스트링으로 넣을까요?

2021-08-22 15:24 UTC, jiyong1 commented on server/src/models/product/entities/product.entity.ts
> +  category: Category;
넵 근데 이부분 논의 해봐야하긴 할 것 같습니다 ..
저는 disabled 태그가 뭔지.. 애매하더라구요

2021-08-22 15:32 UTC, cothis commented on server/src/models/product/entities/product.entity.ts
> +  category: Category;
해당 사항 수정했습니다.

2021-08-23 04:39 UTC, cothis commented
merge 후, 또 개발하면서 필요한 부분들 수정해나가겠습니다

2021-08-23 04:40 UTC, CurlyBat approved these changes
말씀하신대로 개발하면서 필요한 부분 조금씩 고쳐나가는 걸로~
이번 주 한 주도 화이팅입니다

2021-08-23 04:52 UTC, jiyong1 approved these changes
고생하셨습니다 !!

2021-08-23 04:52 UTC, jiyong1 commented on server/src/models/product/entities/product.entity.ts
> +  @ManyToMany(() => Category, (category) => category.products)
감사합니다 !

2021-08-23 04:53 UTC, TsooranKim approved these changes
계속 고쳐 나가시죠!

2021-08-23 04:56 UTC, merged