[feature/#6] frontend 환경 설정
woowa-techcamp-2021/store-1 pull request #9
Opened 2021-08-11 01:06 UTC by jiyong1

## :bookmark_tabs: 제목

- webpack, babel 설정
- 테스트 환경 설정

## :heavy_check_mark: 셀프 체크리스트

> ~최소 2명 이상의 assign을 받아야만 Merge 가능합니다.~

- [x] Warning Message가 발생하지 않았나요?
- [x] Coding Convention을 준수했나요?

## :speech_balloon: 작업 내용

> 구현 내용 및 작업 했던 내역

- webpack이 dev, prod에 따라 다르게 빌드 됩니다.
- babel 설정을 완료하였습니다.
- 테스트 환경을 설정하였습니다.
  - 간단한 테스트를 진행해 봤습니다.
- 리액트 렌더링에 성공하였습니다.

## :construction: PR 특이 사항

> PR을 볼 때 주의깊게 봐야하거나 말하고 싶은 점

- webpack 로더나 플러그인 추가하시고 싶은 사항이 있으시다면 말씀해주세요.
- directory 구조를 보시고 변경 하시고 싶은 사항을 말씀해주세요.
- test code에 대한 이해가 필요합니다.

## 🕰 실제 소요 시간

> 1 mh

2021-08-11 01:14 UTC, cothis approved these changes
고생하셨습니다! 소요시간 1시간 맞나여? 큐ㅠㅠ

2021-08-11 01:14 UTC, cothis commented on client/package.json
> +    "dev": "NODE_ENV=development webpack serve --config webpack.config.ts --open",
--open 옵션은 뭔지 궁금합니다.

2021-08-11 01:14 UTC, cothis commented on client/src/main.tsx
> +import React from 'react';
이 임포트문은 없으면 동작안하는지요??

2021-08-11 01:14 UTC, cothis commented on client/test/App.test.tsx
> +test('render App', () => {
오 멋진 첫 테스트 코드

2021-08-11 01:14 UTC, cothis commented on client/tsconfig.json
> +    "jsx": "react-jsx",
굳!

2021-08-11 01:14 UTC, cothis commented on client/test/transform/fileTransform.js
> +      module.exports = {
리턴으로 코드를 리턴하네요..희한

2021-08-11 02:07 UTC, TsooranKim requested changes
제가 테스트 코드 쪽은 아직은 아는게 없어서 우선 테스트 쪽 제외하고 리뷰 달았습니다!

아참! `yarn`으로 사용해주셨으면 합니다. `package-lock.json`은 제거하고요.

2021-08-11 02:07 UTC, TsooranKim commented on client/webpack/webpack.config.prod.ts
> +  devtool: 'source-map',
```suggestion
```

production 코드에서 디버깅을 해보려면 필요할 수 있는데 end user에게는 아무련 영향이 없으므로 없어도 된다고 생각됩니다.

2021-08-11 02:07 UTC, TsooranKim commented on client/webpack/webpack.config.common.ts
> +import webpack, { Configuration } from 'webpack';
```suggestion
import { Configuration } from 'webpack';
```

2021-08-11 02:13 UTC, CurlyBat commented on client/package.json
> +    "dev": "NODE_ENV=development webpack serve --config webpack.config.ts --open",
--open 옵션을 주게되면 devserver가 열리면 바로 브라우저에 페이지가 열립니다. 편하다 생각해서 넣은 옵션입니다.
혹 불편하시면 빼도 괜찮습니다

2021-08-11 02:14 UTC, CurlyBat commented on client/src/main.tsx
> +import React from 'react';
현재 작동하는데는 문제가 없는데, 테스트 코드에서는 import문이 빠지게 되면 잘 작동하지 않아 다시 넣어둔 부분입니다.

이부분은 추후 다시 제가 확인하고 처리하도록 하겠습니다.

2021-08-11 02:15 UTC, CurlyBat commented on client/.gitignore
> +node_modules
넵 수정하겠습니다

2021-08-11 02:16 UTC, CurlyBat commented on client/webpack/webpack.config.common.ts
> +    new CleanWebpackPlugin(),
아 이부분은 잘 몰랐네요. 또 하나 배워갑니다~
바로 수정하겠습니다!

2021-08-11 02:17 UTC, CurlyBat commented on client/package.json
> +    "dev": "NODE_ENV=development webpack serve --config webpack.config.ts --open",
이부분도 빼겠습니다

2021-08-11 02:23 UTC, CurlyBat commented on client/webpack/webpack.config.dev.ts
> +          },
기존 웹팩 설정을 가져와서 사용하는 과정에서 저부분을 고려하지 않았네요

좀 더 신경쓰겠습니다 😢

2021-08-11 04:58 UTC, CurlyBat commented on client/webpack/webpack.config.dev.ts
> +    contentBase: './public',
현 시점에서 특별한 의도가 있는 것은 아니지만, 백엔드 api에 fetch를 할 수 없는 개발단계에서 

임시로 서버에서 json을 받아왔다고 가정하고

json파일을 public에 넣어놓고 프론트에서 fetch해서 접근하는 용도로 사용했던 옵션입니다.

2021-08-11 05:02 UTC, CurlyBat commented on client/src/main.tsx
> +import React from 'react';
https://ko.reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html

확인해보니, import React문을 생략하기 위한 옵션으로 저희가 어제 tsconfig에서 jsx를 react-jsx으로 주었는데 ts 옵션을 주었을 때 VS code 상에서는 문제가 없으나

실 작동은 문제가 있었습니다. 그 문제를 해결하기 위에 위에 걸어 놓은 링크에서

```json
{
  "presets": [
    ["@babel/preset-react", {
      "runtime": "automatic"
    }]
  ]
}
```
babel config를 수정해주니 import문이 없어도 테스트, 실 작동 모두 잘 되는 상태가 되었습니다.
이렇게 수정하여 커밋하겠습니다

2021-08-11 05:26 UTC, cothis commented on client/src/main.tsx
> +import React from 'react';
오호 감사합니다!!

2021-08-11 06:42 UTC, TsooranKim approved these changes
고생하셨습니다!

2021-08-11 07:24 UTC, merged

2021-08-13 06:08 UTC, edegiil commented on client/package.json
> +}
package.json을 잘 만드셨네요

2021-08-13 06:10 UTC, yoonminsang commented on client/babel.config.js
> +  api.cache(true);
오 이거먼가요?? 캐시를 여기서 하네요

2021-08-13 06:15 UTC, edegiil commented on client/webpack/webpack.config.prod.ts
> +        use: [MiniCssExtractPlugin.loader, 'css-loader', 'sass-loader'],
styled component를 사용하면 sasss-loader는 필요없지 않을까 라는 생각이 있습니다..

2021-08-13 06:15 UTC, CurlyBat commented on client/babel.config.js
> +  api.cache(true);
https://babeljs.io/docs/en/config-files#apicache

babel 쪽 캐싱이라서  config을 다시 실행하는 것을 막아주는 옵션입니다

2021-08-13 06:17 UTC, CurlyBat commented on client/webpack/webpack.config.prod.ts
> +        use: [MiniCssExtractPlugin.loader, 'css-loader', 'sass-loader'],
네 맞습니다. 개발하면서 필요 없는게 확실해지면 뺄 생각을 하고 있었습니다.
일단 기존에 사용하던 설정을 가져와서 ㅜ

2021-08-20 05:43 UTC, KangyeolLee reviewed
무야호

2021-08-20 05:43 UTC, KangyeolLee commented on client/babel.config.js
> +  api.cache(true);
오 저도 배워갑니다~~

2021-08-20 05:43 UTC, KangyeolLee commented on client/package.json
> +}
json.package를 잘 만드셨네요

2021-08-20 05:43 UTC, KangyeolLee commented on client/test/App.test.tsx
> +test('render App', () => {
오 멋진 척 테스트코드로 읽었습니다

2021-08-20 05:54 UTC, HanCheo reviewed
홀리몰리

2021-08-20 05:54 UTC, HanCheo commented on client/babel.config.js
> +  api.cache(true);
이건 저도 배워갑니다~~ 대박쓰

2021-08-20 05:54 UTC, HanCheo commented on client/package.json
> +}
pac.jsonage를 잘 만드셨네요