[feature/#57] oauth 인증 및 jwt 발급
woowa-techcamp-2021/store-1 pull request #95
Opened 2021-08-23 16:50 UTC by cothis

## :bookmark_tabs: 제목

oauth 인증, jwt 발급까지 했습니다.
jwt 발급하면 json으로 리턴됩니다.

## :heavy_check_mark: 셀프 체크리스트

> ~최소 2명 이상의 assign을 받아야만 Merge 가능합니다.~

- [x] Warning Message가 발생하지 않았나요?
- [x] Coding Convention을 준수했나요?

## :speech_balloon: 작업 내용

> 구현 내용 및 작업 했던 내역

- auth module

## :construction: PR 특이 사항

> PR을 볼 때 주의깊게 봐야하거나 말하고 싶은 점

## 🕰 실제 소요 시간

> 6 mh

2021-08-23 16:51 UTC, cothis commented
자세한 코드 설명은 내일 아침에 드릴게요.

2021-08-23 18:46 UTC, TsooranKim commented
> 자세한 코드 설명은 내일 아침에 드릴게요.

기대하고 있겠습니다!

2021-08-24 08:41 UTC, jiyong1 reviewed
잉 댓글이 안달아져요 ..

2021-08-24 08:41 UTC, CurlyBat approved these changes
고생하셨습니다
authguard가 어떤 방식으로 작동하는지도 알려주시면 좋을것 같습니다

2021-08-24 08:41 UTC, CurlyBat commented on client/src/pages/Signin.tsx
> +    location.href = 'http://localhost:8080/api/v1/auth';
이부분은 나중에 수정하는 걸로..

2021-08-24 08:41 UTC, CurlyBat commented on server/package.json
> +    "randomstring": "^1.2.1",
이것도 뭐 uuid같은건가봐요?

2021-08-24 08:41 UTC, CurlyBat commented on server/src/auth/auth.controller.ts
> +    res.cookie('jwt', this.jwtService.sign({ userId: '123' }));
이부분 빼야하지않나요?

2021-08-24 08:41 UTC, CurlyBat commented on server/src/auth/local.strategy.ts
> +    console.log(loginId, password);
앗.. 콘솔

2021-08-24 08:41 UTC, CurlyBat commented on server/src/config/jwt.service.ts
> +  // }
이부분은 어떻게 된건가요?

2021-08-24 08:41 UTC, CurlyBat commented on server/src/auth/auth.controller.ts
> +    console.log(code, state);
여기도 콘솔이 🎮

2021-08-24 08:41 UTC, jiyong1 commented on server/src/auth/local.strategy.ts
> +    console.log(loginId, password);
콘솔.. ㅋㅋㅋㅋㅋ

2021-08-24 08:44 UTC, cothis commented on client/src/pages/Signin.tsx
> +    location.href = 'http://localhost:8080/api/v1/auth';
넵!!

2021-08-24 08:44 UTC, cothis commented on server/package.json
> +    "randomstring": "^1.2.1",
맞습니다! 랜덤한 문자열 만들어줍니다.

2021-08-24 08:44 UTC, cothis commented on server/src/auth/auth.controller.ts
> +    res.cookie('jwt', this.jwtService.sign({ userId: '123' }));
테스트코드 만들어놓고 고대로 올려버렸네요..지우겠습니다

2021-08-24 08:44 UTC, cothis commented on server/src/auth/local.strategy.ts
> +    console.log(loginId, password);
콘솔...확인용이 남아있네요..지우겠습니다

2021-08-24 08:45 UTC, cothis commented on server/src/config/jwt.service.ts
> +  // }
이 부분은 혹시 추후에 다른 사용법을 알게되서 쓸까봐 지우지 않고 주석만 해놨습니다

2021-08-24 08:45 UTC, cothis commented on server/src/auth/auth.controller.ts
> +    console.log(code, state);
콘솔..감사합니다.

2021-08-24 08:45 UTC, jiyong1 approved these changes
고생하셨습니다.. 저는 어질어질하네요 .. ㅠㅠ

2021-08-24 08:45 UTC, jiyong1 commented on server/src/auth/jwt-auth.guard.ts
> +export class JwtAuthGuard extends AuthGuard('jwt') {}
authGuard가 뭔지 궁금하네여.. ㅋㅋㅋㅋ

2021-08-24 08:45 UTC, jiyong1 commented on server/src/auth/auth.controller.ts
> +  async requestRedirect(@Session() session: Record<string, any>, @Req() req: Request, @Res() res: Response) {
오호라 이렇게 인자를 받는군요..

2021-08-24 08:45 UTC, jiyong1 commented on server/src/auth/auth.module.ts
> +      useFactory: async (jwtConfigService: JwtConfigService) => ({
useFactory는 뭐하는 친구인지 설명해주세요 !

2021-08-24 08:46 UTC, cothis commented
<img width="552" alt="스크린샷 2021-08-24 오후 5 45 55" src="https://user-images.githubusercontent.com/50898502/130586550-28f2cf46-5764-41f2-922b-28f8accfc1b0.png">
가드에서 실패시 이런식으로 리턴됩니다.

2021-08-24 08:48 UTC, cothis commented on server/src/auth/auth.module.ts
> +      useFactory: async (jwtConfigService: JwtConfigService) => ({
네 원래 공식문서에는
``` ts
JwtModule.register({
        secret: 'secretkeyasdfasdf',
        signOptions: { expiresIn: '1d', algorithm: 'HS256' },
}
```
형태로 등록하는데, 동적으로 jwtConfigService를 주입받아서 넣으려면 이런식으로 팩토리를 사용해서 팩토리에 주입받아서 처리하는 방법을 제시해주더라구요.
그래서 이렇게 사용하고 있습니다.

2021-08-24 08:48 UTC, cothis commented on server/src/auth/auth.controller.ts
> +  async requestRedirect(@Session() session: Record<string, any>, @Req() req: Request, @Res() res: Response) {
넵! 신기하죠!

2021-08-24 08:50 UTC, cothis commented on server/src/auth/jwt-auth.guard.ts
> +export class JwtAuthGuard extends AuthGuard('jwt') {}
일종의 필터링같은 역할을 합니다. 컨트롤러 로직 들어오기 전에 Guard에 등록한 validate 를 통과해야만 들어와집니다.
그리고 그 validate의 리턴값은 req에 담겨들어오는걸로 파악해써요.

2021-08-24 08:51 UTC, jiyong1 commented
가드에 실패하면 statusCode 401 뿐만아니라 실제 response status도 401이 되나요 ?!

2021-08-24 08:52 UTC, cothis commented on server/src/auth/jwt-auth.guard.ts
> +export class JwtAuthGuard extends AuthGuard('jwt') {}
정확히는 req에 user 로 들어옵니다!

2021-08-24 08:59 UTC, cothis commented
<img width="988" alt="스크린샷 2021-08-24 오후 5 59 28" src="https://user-images.githubusercontent.com/50898502/130588576-f001dddb-eb41-47a2-8452-243559da0676.png">
넵 실제 Response Status도 401입니다.

2021-08-24 09:04 UTC, cothis commented
https://github.com/mikenicholson/passport-jwt#extracting-the-jwt-from-the-request
Jwt Extractor 는 이거 보고 직접 정의했습니다. 공식문서는 header에서 토큰 가져오는 방식인데 우리는 쿠키로 쓰는 방식이다보니
그거에 맞게 수정했어요.
<img width="793" alt="스크린샷 2021-08-24 오후 6 04 03" src="https://user-images.githubusercontent.com/50898502/130589195-11a6fbf4-1fcd-4c01-980f-bc1839573678.png">

2021-08-24 09:34 UTC, TsooranKim requested changes
![image](https://user-images.githubusercontent.com/5162089/130593549-aa85b842-c063-4c71-aedf-616204b5861c.png)

service가 entity를 반환하는데 dto로 처리하면 어떨까요?
근데 사실 규모가 작아서 크게 상관없기는 하지만 말이에요.
음... 번거로운 작업하나 더 늘리는거려나요?

제가 passport를 모르니 그쪽으로는 리뷰가 불가능하네요 ㅠ 좀 봐야겠어요.

2021-08-24 09:34 UTC, TsooranKim commented on server/src/auth/auth.controller.ts
> +  }
```suggestion
  @Get('/logout')
  async logout(@Req() req: Request, @Res({ passthrough: true }) res: Response) {
    res.clearCookie('jwt');
    req.session.destroy();
    return { ok: true };
  }
```

`@Res({ passthrough: true }) res: Response`로 해줘야 정상적으로 return이 되는것으로 알고 있습니다.

`destroy()`는 callback이 없어도 되지 않나요?

2021-08-24 09:34 UTC, TsooranKim commented on server/package.json
> +    "node-fetch": "^2.6.1",
그냥 한 말입니다!

2021-08-24 09:34 UTC, TsooranKim commented on server/src/auth/auth.service.ts
> +  getRequestUrl() {
```suggestion
  getKakaoOauthUrl() {
```

이건 어떤가요?

2021-08-24 09:34 UTC, TsooranKim commented on server/src/auth/auth.service.ts
> +    if (state !== STATE) throw new Error('STATE가 다릅니다. csrf 공격이 의심됩니다.');
CustomError가 없군요 ㅠ 만들어야 겠어요.
ErrorHandler도 같이요. Spring MVC의 `@ExceptionHandler`같은거요.

2021-08-24 09:34 UTC, TsooranKim commented on server/src/auth/auth.service.ts
> +  async oauth(code: string, state: string) {
```suggestion
  async kakaoOAuth(code: string, state: string) {
```
는 어떤가요?

2021-08-24 09:34 UTC, TsooranKim commented on server/src/auth/auth.service.ts
> +    });
이게 fetch와 동일하다면 4xx 에러가 자동으로 처리가 안될탠데 말이에요.
axios로 바꾼다음에 try catch하는게 어떨가요?
그런다음 문제 생기면 CustomError를 throw 하고요.

2021-08-24 09:34 UTC, TsooranKim commented on server/src/auth/auth.service.ts
> +  async getUserInfo(accessToken: string) {
```suggestion
  async getKakaoUserInfo(accessToken: string) {
```

사실 우리가 카카오 밖에 없어서 크게 문제될 건 없지만 그래도 kakao를 붙이면 좋겠어요.

2021-08-24 09:34 UTC, TsooranKim commented on server/src/auth/auth.service.ts
> +  async validateUser(loginId: string, password: string): Promise<Partial<User>> {
```suggestion
  async validateUser(loginId: string, password: string): Promise<Partial<User> | null> {
```

반환타입에 `null`이 빠지면 반드시 호출시 `Partial<User>`를 넘겨주거나 그렇지 못하면 throw를 해야합니다.
대부분의 라이브러리나 기본 js도 그렇게 돼 있어요.

2021-08-24 09:34 UTC, TsooranKim commented on server/src/auth/jwt.strategy.ts
> +  async validate(payload: any) {
```suggestion
  async validate(payload: { userId: string }) {
```

any를 피해요~~

2021-08-24 09:34 UTC, TsooranKim commented on server/src/auth/auth.service.ts
> +    if (state !== STATE) throw new Error('STATE가 다릅니다. csrf 공격이 의심됩니다.');
아참 nest.js에서 기본으로 제공해주는 Error들 많을 탠데 말이에요.

2021-08-24 09:34 UTC, TsooranKim commented on server/src/config/config.yaml.sample
> +  rest_api: kakao_api
```suggestion
  kakao_client_id: kakao_api
```

oauth 규격에 맞게 client_id로 지정하는게 좋아보이지만 크게 상관은 없습니다.

2021-08-24 09:34 UTC, TsooranKim commented on server/src/models/users/entities/user.entity.ts
> +@Entity({ name: 'tuser' })
그냥 `user`는 안되는건가요? ㅠ

2021-08-24 10:44 UTC, TsooranKim commented on server/src/config/jwt.service.ts
> +  // }
아항 이거 제가 만들었던가 보네요

2021-08-24 10:44 UTC, TsooranKim commented on server/src/auth/auth.controller.ts
> +    console.log(code, state);
콘솔 찾기 마스터 ㅋㅋ

2021-08-24 12:09 UTC, cothis commented on server/package.json
> +    "node-fetch": "^2.6.1",
client 에 맞춰서 axios 를 쓰려고 하다가, nestjs에서 rxjs 로 돌아가는걸 추천해줘서.. rxjs로 해보다가 롤백하고 fetch 로 갈아탔습니다..ㅜㅜ

2021-08-24 12:09 UTC, cothis commented on client/src/pages/Signin.tsx
> +  };
저부분은 아마 단순 a tag나 이런걸로 리팩토링될것 같습니다!

2021-08-24 12:10 UTC, cothis commented on server/src/auth/auth.controller.ts
> +  @Get('/')
변경했습니다!

2021-08-24 12:10 UTC, cothis commented on server/src/auth/auth.controller.ts
> +  @Get('redirect')
변경했습니다!

2021-08-24 12:11 UTC, cothis commented on server/src/auth/auth.service.ts
> +  async getUserInfo(accessToken: string) {
변경했습니다!

2021-08-24 12:12 UTC, cothis commented on server/src/auth/auth.service.ts
> +  async validateUser(loginId: string, password: string): Promise<Partial<User>> {
null 도 Partial<User>의 일부라고 생각했는데, 말씀대로 변경했습니다!

2021-08-24 12:13 UTC, cothis commented on server/src/auth/jwt.strategy.ts
> +  async validate(payload: any) {
변경했습니다!

2021-08-24 12:14 UTC, cothis commented on server/src/config/config.yaml.sample
> +  rest_api: kakao_api
변경했습니다!

2021-08-24 12:14 UTC, TsooranKim commented on server/src/auth/auth.service.ts
> +    if (state !== STATE) throw new Error('STATE가 다릅니다. csrf 공격이 의심됩니다.');
```typescript
import { HttpException, HttpStatus } from '@nestjs/common';

throw new HttpException('STATE가 다릅니다. csrf 공격이 의심됩니다.', HttpStatus.BAD_REQUEST);
```

이런식으로 하세요.
그냥 throw 하면 500번 에러가 나요.

2021-08-24 12:30 UTC, cothis commented on server/src/models/users/entities/user.entity.ts
> +@Entity({ name: 'tuser' })
되네요!!!

2021-08-24 12:37 UTC, cothis commented on server/src/auth/auth.controller.ts
> +    res.cookie('jwt', this.jwtService.sign({ userId: '123' }));
저건 제가 jwt 테스트한다고 넣어놨던 코드입니다. 지웠어여!

2021-08-24 12:38 UTC, cothis commented on client/src/pages/Signin.tsx
> +    location.href = 'http://localhost:8080/api/v1/auth';
넵 아니면 location url 같은걸 써도 되지 않을까..하고 생각해봅니다!

2021-08-24 12:38 UTC, cothis commented on server/src/auth/auth.service.ts
> +  getRequestUrl() {
변경했습니다!

2021-08-24 12:40 UTC, cothis commented on server/src/auth/auth.controller.ts
> +  }
맞아요 res.send 로 직접 명시하거나 passthrough 줘야되는데 빼먹었네요. 고쳤습니다
session destory 는 콜백필요합니다! 
![스크린샷 2021-08-24 오후 9 40 26](https://user-images.githubusercontent.com/50898502/130617943-1e83863a-b437-40f8-ac43-fe033082acdf.png)

2021-08-24 12:41 UTC, cothis commented on server/src/auth/auth.service.ts
> +  async oauth(code: string, state: string) {
변경했습니다!

2021-08-24 12:43 UTC, cothis commented on server/src/auth/auth.service.ts
> +    if (state !== STATE) throw new Error('STATE가 다릅니다. csrf 공격이 의심됩니다.');
if (state !== STATE) throw new BadRequestException('STATE가 다릅니다. csrf 공격이 의심됩니다.');
로 변경했습니다!

2021-08-24 12:50 UTC, cothis commented on server/src/auth/auth.controller.ts
> +  }
api/v1/users/me 로 가도록 변경했습니다.

2021-08-24 13:05 UTC, cothis commented on server/package.json
> +    "node-fetch": "^2.6.1",
axios로 적용했습니다.

2021-08-24 15:35 UTC, TsooranKim approved these changes
고생하셨습니다!

2021-08-24 15:35 UTC, TsooranKim commented
서버 작업 때문에 대신 머지 합니다.

2021-08-24 15:36 UTC, merged